---
title: "Field Sampling"
author: "Hazel de Haas"
date: "30/10/2021"
output:
  pdf_document: default
  html_document: default
---


```{r}
library(tidyverse)
library(ggplot2)

```

#Stacked graph 

```{r}
biod1 <- read.csv("biodiversity.csv")

ww <- aggregate(list(biod1$n), by = list(biod1$species, biod1$abiotic_hab), sum)
colnames(ww) <- c("species", "habitat", "number")
library(viridis)
wwgraph <- ggplot(data= ww, aes(fill= species, y = number, x = habitat)) +
                    geom_bar(position="stack", stat="identity")+
   theme_classic() + labs(x = "Substrate Type", y = "Number of Individuals")
wwgraph   
```


#Code for SW for each substate in each quadrat
```{r}
species_data <- read.csv("biodiversity.csv")
percent_cover <- read.csv("percent_cover.csv")

# filter species datat
quadratSW_data <- species_data %>%
  drop_na(species) %>%
  group_by(vertical_transect, quadrat, abiotic_hab, species) %>%
  summarize(total_species = sum(n)) 

substrate_bio <- species_data %>%
  drop_na(species) %>%
  group_by(abiotic_hab, species) %>%
  summarize(n_occurences = sum(n)) 

swfunction = function(data, transect, quadrat, abiotic_hab){

  data_temp = data[which(data$vertical_transect == transect),]
  data_temp = data_temp[which(data_temp$quadrat == quadrat),]
  temp_data = data_temp[which(data_temp$abiotic_hab == abiotic_hab),]

  sum = sum(temp_data$total_species)
  p_ln_vec = c()
  for(i in 1:nrow(temp_data)){
      #it doesn't matter but it works
    p = data.frame((temp_data[i, "total_species"][1]))[1,1]/sum
    ln_p = log(p)
    p_ln_p = p*ln_p
    p_ln_vec = c(p_ln_vec, p_ln_p)
  }
  H = sum(p_ln_vec)*-1
  return(H)
}

# we have our function
# now we need to use it to fill up a dataframe
H_df = data.frame(transect = integer(), 
                  quadrat = integer(), 
                  abiotic_hab = character(),
                  H = double())

for(transect_set in unique(quadratSW_data$vertical_transect)) {
  for(quadrat_set in unique(quadratSW_data$quadrat)) {
    
    # set temp data 
    subset_df = quadratSW_data %>% 
      filter(quadrat == quadrat_set) %>% 
      filter(vertical_transect == transect_set)
    
    for(abiotic_hab_set in unique(subset_df$abiotic_hab)) {
        H = swfunction(data, transect_set, quadrat_set, abiotic_hab_set)
        temp_df = data.frame(transect_set, quadrat_set, abiotic_hab_set, H)
        H_df = rbind(H_df, temp_df)
    }
  }
}

```

#SW for total substrate in all quadrats
```{r}


H_bedrock = swfunction(substrate_bio, "bedrock")
H_pebbles = swfunction(substrate_bio, "pebbles")
H_boulder = swfunction(substrate_bio, "boulder")
H_cobble = swfunction(substrate_bio, "cobble")

#put these values in a table - can't do stats cause its only values per substrate type

#H_bedrock = 1.080693
#H_pebbles = 0.728715
#H_cobble =  1.210030
#H_boulder = 1.056021



```

| Boulder | Cobble | Pebbles |
|------|------|------|
| H | 1.056021 | 1.210030 | 0.728715 | 





#Anova for Quadrat SW
```{r}
bedrockfree_H_df <- H_df %>% 
  filter(abiotic_hab_set != "bedrock")

weiner_anova <- aov(H~abiotic_hab_set, data = bedrockfree_H_df)
summary(weiner_anova)

#p-value is not significant :(
```

#Box plot for Quadrat SW
```{r}
library(ggplot2)
library(viridis)

my_cols = c("boulder" = "blue1", "cobble" = "red", "pebbles" = "yellow")

weiner_quadrat_boxplot <- ggplot(bedrockfree_H_df, aes(x = abiotic_hab_set, y = H, fill = abiotic_hab_set )) +
  geom_boxplot(alpha = 0.4) +
  theme_classic() +
  scale_color_manual(values = my_cols) +
  scale_fill_manual(values = my_cols) +
  labs(x = "Substrate Type", y = "Shannon-Wiener Index")
weiner_quadrat_boxplot

  
```



```{r}

library(tidyverse)
library(ggplot2)

data <- species_data
# cleaning the data
clean_data <- data %>%
  select(abiotic_hab, species, n) %>%
  group_by(abiotic_hab)

summary(clean_data)

# Cole's code for species richness per quadrat
quad_richness <- data %>%
  drop_na(n) %>%
  group_by(vertical_transect,quadrat) %>%
  summarize(n_spp = n())

# finding species richness for each abiotic habitat type
boulder_richness <- clean_data %>%
  filter(abiotic_hab == "boulder") %>%
  distinct()

bedrock_richness <- clean_data %>%
  filter(abiotic_hab == "bedrock") %>%
  distinct()

cobble_richness <- clean_data %>%
  filter(abiotic_hab == "cobble") %>%
  distinct()

pebbles_richness <- clean_data %>%
  filter(abiotic_hab == "pebbles") %>%
  distinct()

sand_richness <- clean_data %>%
  filter(abiotic_hab == "sand") %>%
  distinct()

# total n of each species for each substrate type 
boulder_data <- clean_data %>%
  filter(abiotic_hab == "boulder")

aggboulder<- aggregate(list(boulder_data$n), by = list(boulder_data$species), sum)

bedrock_data <- clean_data %>%
  filter(abiotic_hab == "bedrock")

aggbedrock <- aggregate(list(bedrock_data$n), by = list(bedrock_data$species), sum)

cobble_data <- clean_data %>%
  filter(abiotic_hab == "cobble")

aggcobble <- aggregate(list(cobble_data$n), by = list(cobble_data$species), sum)

pebbles_data <- clean_data %>%
  filter(abiotic_hab == "pebbles")

aggpebbles <- aggregate(list(pebbles_data$n), by = list(pebbles_data$species), sum)

sand_data <- clean_data %>%
  filter(abiotic_hab == "sand")

aggsand <- aggregate(list(sand_data$n), by = list(sand_data$species), sum)

ggplot(data, aes(x = abiotic_hab, y = species)) +
  geom_boxplot()

```

